"""Add dietary_preferences field to User model

Revision ID: 53a1aad6a9a2
Revises: b585698d48ee
Create Date: 2025-05-06 03:16:16.939165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a1aad6a9a2'
down_revision = 'b585698d48ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dietary_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dietary_preferences')

    # ### end Alembic commands ###
