"""empty message

Revision ID: 557136dc0ab5
Revises: 2286c5b07fdc
Create Date: 2024-09-18 08:58:37.780400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557136dc0ab5'
down_revision = '2286c5b07fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.alter_column('ingredient',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('ingredient',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
